ATTACH DATABASE '00_rawData/SQLite_FIADB_ENTIRE.db' AS FIA;
ATTACH DATABASE '00_rawData/N-K_Table_1.db' AS NK;

-- StandInit_cond.Stand_ID = concatenation of: 
-- STATECD(4) + 
-- INVYR(4) + CYCLE(2) + SUBCYCLE(2) + 
-- UNITCD(2) + COUNTYCD(3) + PLOT(5) + CONDID (1)

-- In NK, stand_ids appear to be
-- STATECD(2)
-- YEAR(4)
-- UNITCD(2)
-- COUNTYCD(3)
-- PLOT(5)

WITH NK_EXPANDED AS (
  SELECT
    SUBSTR("FIA plot code", 1, 2) AS STATECD,
    SUBSTR("FIA plot code", 3, 4) AS INVYR,
    SUBSTR("FIA plot code", 7, 2) AS UNITCD,
    SUBSTR("FIA plot code", 9, 3) AS COUNTYCD,
    SUBSTR("FIA plot code", 12, 5) AS PLOT,
    *
--  FROM PLOTS
  FROM NK.PLOTS
),
FIA_CONVERTED AS (
  SELECT
    STATECD,
    INVYR,
    UNITCD,
    COUNTYCD,
    CONDID,
    PLOT,
    STDAGE,
    FLDAGE,
    SICOND,
    SICOND_FVS,
    SLOPE,
    ASPECT,
    (BALIVE * 0.092903 / 0.404686) AS BALIVE_METRIC,
    (NBR_LIVE_STEMS / 0.404686) AS TPH
  FROM FIA.COND
)
-- SELECT * FROM NK_EXPANDED;
SELECT
  NK_EXPANDED."FIA plot code",
  NK_EXPANDED.UNITCD,
  NK_EXPANDED.STATECD,
  NK_EXPANDED.COUNTYCD,
  NK_EXPANDED.PLOT,
  FIA_CONVERTED.CONDID,
  NK_EXPANDED.INVYR AS "NK Year",
  FIA_CONVERTED.INVYR,
  NK_EXPANDED."Starting stand age",
  FIA_CONVERTED.STDAGE,
  FIA_CONVERTED.FLDAGE,
  NK_EXPANDED."Site index",
  FIA_CONVERTED.SICOND,
  FIA_CONVERTED.SICOND_FVS,
  NK_EXPANDED."Slope (%)",
  FIA_CONVERTED.SLOPE,
  NK_EXPANDED."Aspect (degrees)",
  FIA_CONVERTED.ASPECT,
  NK_EXPANDED."Basal area (m2/ha)",
  FIA_CONVERTED.BALIVE_METRIC,
  NK_EXPANDED."Trees per hectare",
  FIA_CONVERTED.TPH
FROM NK_EXPANDED
JOIN FIA_CONVERTED ON
  NK_EXPANDED.UNITCD = FIA_CONVERTED.UNITCD AND
  NK_EXPANDED.STATECD = FIA_CONVERTED.STATECD AND
  NK_EXPANDED.COUNTYCD = FIA_CONVERTED.COUNTYCD AND
  NK_EXPANDED.PLOT = FIA_CONVERTED.PLOT AND
  NK_EXPANDED."Starting stand age" = FIA_CONVERTED.STDAGE;

