ATTACH DATABASE '00_rawData/SQLite_FIADB_ENTIRE.db' AS FIA;
ATTACH DATABASE '00_rawData/N-K_Table_1.db' AS NK;

WITH NK_EXPANDED AS (
  SELECT
    SUBSTR("FIA plot code", 1, 2) AS STATECD,
    SUBSTR("FIA plot code", 3, 4) AS INVYR,
    SUBSTR("FIA plot code", 7, 2) AS UNITCD,
    SUBSTR("FIA plot code", 9, 3) AS COUNTYCD,
    SUBSTR("FIA plot code", 12, 5) AS PLOT,
    *
  FROM NK.PLOTS
),
FIA_CONVERTED AS (
  SELECT
    STATECD,
    INVYR,
    CYCLE,
    SUBCYCLE,
    UNITCD,
    COUNTYCD,
    CONDID,
    PLOT,
    STDAGE,
    FLDAGE,
    SICOND,
    SICOND_FVS,
    SLOPE,
    ASPECT,
    (BALIVE * 0.092903 / 0.404686) AS BALIVE_METRIC,
    (NBR_LIVE_STEMS / 0.404686) AS TPH
  FROM FIA.COND
)
SELECT
  NK_EXPANDED."FIA plot code",
  FORMAT(
    '%04d%04d%02d%02d%02d%03d%05d%01d',
    FIA_CONVERTED.STATECD,
    FIA_CONVERTED.INVYR,
    FIA_CONVERTED.CYCLE,
    FIA_CONVERTED.SUBCYCLE,
    FIA_CONVERTED.UNITCD,
    FIA_CONVERTED.COUNTYCD,
    FIA_CONVERTED.PLOT,
    FIA_CONVERTED.CONDID
  ) AS STAND_ID,
  NK_EXPANDED.UNITCD,
  NK_EXPANDED.STATECD,
  NK_EXPANDED.COUNTYCD,
  NK_EXPANDED.PLOT,
  NK_EXPANDED.INVYR AS "NK Year",
  FIA_CONVERTED.INVYR,
  FIA_CONVERTED.CYCLE,
  FIA_CONVERTED.SUBCYCLE,
  FIA_CONVERTED.CONDID,
  NK_EXPANDED."Starting stand age",
  FIA_CONVERTED.STDAGE,
  FIA_CONVERTED.FLDAGE,
  NK_EXPANDED."Slope (%)",
  FIA_CONVERTED.SLOPE,
  NK_EXPANDED."Aspect (degrees)",
  FIA_CONVERTED.ASPECT,
  NK_EXPANDED."Basal area (m2/ha)",
  FIA_CONVERTED.BALIVE_METRIC
FROM NK_EXPANDED
JOIN FIA_CONVERTED ON
  NK_EXPANDED.UNITCD = FIA_CONVERTED.UNITCD AND
  NK_EXPANDED.STATECD = FIA_CONVERTED.STATECD AND
  NK_EXPANDED.COUNTYCD = FIA_CONVERTED.COUNTYCD AND
  NK_EXPANDED.PLOT = FIA_CONVERTED.PLOT AND
  NK_EXPANDED."Starting stand age" = FIA_CONVERTED.STDAGE AND
  FIA_CONVERTED.INVYR <= 2005;