---
title: "fiaInputs"
author: "Danelle Laflower"
date: "2023-05-10"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
source("Y:/LANDIS/Rcode/landis_source.R")
stateCodesToInclude <- 25 # c(9,23,25,33,36,44,50) # CT Maine MA NH NY RI VT
statesToInclude <- "MA" #(c("NY","ME","NH","VT","CT","MA","RI")  #STATES
minINVYR <- 1999

#
```

#bring in fia data
#pull possible plots and associated ecoregions
#
#
```{r which computer}
whichComputer <-   "danel" #"dml486" #
#
```

```{r fia prep with new source inputs}
source("Y:/FIA/Rcode/FIA_ImportAndProcess_notTrees.R")
source("Y:/FIA/Rcode/fia_source_treesSUBSET.R") #currently New England is the default.  manually set before running

allbioOut <- allbio %>% dplyr::select("CN"=TRE_CN,STATECD,REGIONAL_DRYBIOT, REGIONAL_DRYBIOM)
plotCondStateVar <- c("STATECD","STATE","plotAreaForest","nsubplotsForest","subplotNames","topSTDAGE")
ecoVar <- c("ECOSUBCD")
forestTypeVar <- c("forestTypeGroup","forTypeGroupName")
#
# join plotCondft here
 alltreesPrep <- alltrees %>%
   filter(INVYR>=minINVYR) %>%
      left_join(states) %>%
   left_join(allbioOut) %>% #,by=c("CN"="TRE_CN","STATECD"="STATECD")
   dplyr::select(STATE,STATECD,UNITCD,COUNTYCD,PLOT,PLT_CN,SUBP,INVYR,DIA,CARBON_AG,STATUSCD,REGIONAL_DRYBIOT,TREE) %>% #,TREE,SPCD,DRYBIO_BOLE,DRYBIO_STUMP,DRYBIO_AG,TREE,SPCD,

    unite(concatPlot, STATECD,UNITCD,COUNTYCD,PLOT,sep = "_",remove=FALSE) %>%
    unite(concatSub,STATECD,UNITCD,COUNTYCD,PLOT,SUBP,sep = "_",remove=FALSE) %>%
  left_join(plotCondft) %>% 
   filter(plotAreaForest>=300)
   # filter(plotAreaForest>=(672.4/2))
#
 maTrees <- alltreesPrep %>% 
     filter(STATE %in% c("MA")) 
#
harvPlots <- maTrees %>% 
  #rename(concatPlot=concat) %>% 
  filter(STATUSCD==3) %>% 
  group_by(concatPlot) %>% 
  mutate(harv1=min(INVYR)) %>% 
  dplyr::select(concatPlot,
                STATECD,
                STATE,
                PLT_CN,
                harv1
                ) %>% 
  distinct() %>% 
  group_by(concatPlot,STATECD,STATE,harv1) %>% 
  summarise(nharv=length(PLT_CN)) %>% 
  mutate( harvest="yes") 
# 
plotAGC1 <- maTrees %>% 
  #
  filter(PLOT_STATUS_CD==1) %>% 
  filter(STATUSCD!=0) %>% #not measured trees
  #
  # filter out trees that are not in the target subplots
  mutate(subplotNames=as.character(subplotNames)) %>% 
  
  # IMPORTANT METHODOLOGY NOTE #OKAY FOR MA, BUT CHECK for other areas incase they contain subplots named 101 or greater.
  filter(str_detect(subplotNames,as.character(SUBP))) %>% 
 
  # drop_na(REGIONAL_DRYBIOT) %>% # don't use because it removes harvested trees
  mutate(AGCg=CARBON_AG*453.592,
         AGCMg=AGCg*gramToMegagram,
         AGBg=REGIONAL_DRYBIOT*453.592,
         AGBMg=AGBg*gramToMegagram) 
#

#grouped by forest type # version accounts for dead trees
plotAGCft <- plotAGC1 %>% 
  group_by_at(vars(concatPlot,PLT_CN,PLOT_STATUS_CD,INVYR,STATUSCD,plotCondStateVar,forestTypeVar)) %>% 
  summarise(AGCmerchMg=sum(AGCMg,na.rm=TRUE),
            AGCMg=sum(AGBMg,na.rm=TRUE)/2,
            nStems=length(TREE)) %>% 
  mutate(statusName=ifelse(STATUSCD==1,"live",ifelse(STATUSCD==2,"dead",ifelse(STATUSCD==3,"removed","unk")))) %>% 
  pivot_wider(id_cols=c(concatPlot,PLT_CN,PLOT_STATUS_CD,INVYR,plotCondStateVar,forestTypeVar),names_from=statusName,values_from=c(AGCMg,AGCmerchMg)) %>% 
  dplyr::select(concatPlot,PLT_CN,PLOT_STATUS_CD,INVYR,plotCondStateVar,forestTypeVar,plotAGCMg=AGCMg_live,AGCMg_dead,plotAGCmerchMg=AGCmerchMg_live) %>% 
  # 
  left_join(harvPlots) %>% 
  replace_na(list(harvest="no")) %>% 
  group_by(concatPlot) %>% 
  arrange(concatPlot,INVYR) %>% 
  #
  mutate(firstINVYR=min(INVYR),lastINVYR=max(INVYR)) %>%
  #filter(INVYR ==firstINVYR |INVYR==lastINVYR) %>% 
  mutate(yrsBetween=INVYR-lag(INVYR),
         # GrowthMerch=plotAGCmerchMg-lag(plotAGCmerchMg),
         # Growth=plotAGCMg-lag(plotAGCMg),
         # annGrowth=(Growth/yrsBetween),
         # annGrowthMgHa=annGrowth*(10000/plotAreaForest),
         AGCMgha=plotAGCMg*(10000/plotAreaForest) ,
         annGrowthMgHa=(AGCMgha-lag(AGCMgha))/yrsBetween,
         ageBin=ifelse(topSTDAGE<=20,"0-20",
                       ifelse(topSTDAGE<=100,"21-100",">100")),
         ageBin=factor(ageBin,levels=c("0-20","21-100",">100"))
         ) %>% 
  mutate(harvTime=ifelse(INVYR<harv1,"preHarv",
                         ifelse(INVYR==harv1,"harv1Time",
                                ifelse(INVYR > harv1 & nharv==1,"postHarv",
                                       ifelse(INVYR== (harv1+yrsBetween) & nharv>=2,"harv2Time",
                                              ifelse(INVYR > (harv1+yrsBetween) & nharv==2,"postHarv",
                                                     ifelse(INVYR==harv1+(2*yrsBetween) & nharv>=3,"harv3Time","undefined")))) ) ) ) %>% 
  group_by(concatPlot) %>% 
   mutate(nSubplotChange=ifelse(min(nsubplotsForest)!=max(nsubplotsForest),"change","noChange")) 
####






possibles <- plotCondft %>% filter(STATE=="MA" & 
                        plotAreaForest==672.44 & 
                        PLOT_STATUS_CD==1 & 
                        ECOSUBCD=="M211Cc" & 
                        forTypeGroupName=="mapleBirchBeech" & 
                        topSTDAGE>80)

trees1short <- alltrees %>% 

  filter(INVYR>=1999) %>% 
  
  filter(SUBP<=4) %>% #data for subp numbers greater than 4 are coearsed into the 1-4 design and duplicated - so removing 3/3/23
  
  dplyr::select(INVYR,STATECD,UNITCD,COUNTYCD,PLOT,PLT_CN,SUBP,TREE,CN,STATUSCD,SPCD,SITREE,DIA,TPA_UNADJ,CARBON_AG,HT,ACTUALHT,TREECLCD,AGENTCD) %>% 
  unite(concatPlot,STATECD,UNITCD,COUNTYCD,PLOT,sep="_",remove=FALSE) %>% 
  mutate(AGCg=CARBON_AG*453.592,
         AGCMg=AGCg*gramToMegagram,
         actHeight=ifelse(ACTUALHT==-Inf,NA,ACTUALHT),
         sizeClass = ifelse(DIA>=5,"tree","sap"),
         diacm=DIA*2.54,
         BAm2=pi*(.5*(diacm)/100)^2
  ) %>% 
  group_by(concatPlot,PLOT,SUBP,TREE,CN) %>% 
  arrange(concatPlot,PLOT,SUBP,TREE,CN,INVYR) %>% 
  mutate(treeBAI=(BAm2-lag(BAm2)/(INVYR-lag(INVYR))),Growth_Cg=(AGCg-lag(AGCg)/(INVYR-lag(INVYR)))) 
#
 a <- trees1short %>% left_join(plotCondft) %>% filter(!is.na(meanSICOND)) %>% group_by(SPCD) %>% summarise(maxBAm2=max(BAm2,na.rm=TRUE),lowSI=quantile(meanSICOND,probs=.05),medSI=quantile(meanSICOND,probs=.5),highSI=quantile(meanSICOND,probs=.9))%>% mutate(maxBAft2=maxBAm2*10.76391) 
 #

fiasp <- fia %>% mutate(genuspec=tolower(genuspec))
 b <- a %>% left_join(fiasp) %>% right_join(landisspp)
 #
 # look at summarized BA for possible target plots, "possibles"
 plotout <- trees1short %>% 
   filter(STATUSCD==1) %>% 
   left_join(plotCondft) %>%
   filter(plotAreaForest==672.44) %>% 
#   
   ungroup() %>% 
   mutate(treeBAm2=ifelse(DIA>5,BAm2,NA),
          sapBAm2=ifelse(DIA<5,BAm2,NA)) %>% 
   
   #group_by(concatPlot,PLT_CN,SUBP,TREE) %>% 

  group_by(concatPlot,INVYR,PLT_CN,topSTDAGE) %>% 
  summarise(plotTreeBAm2=sum(treeBAm2,na.rm=TRUE),
            plotSapBAm2=sum(sapBAm2,na.rm=TRUE)) %>% 

   ungroup() %>% 
   mutate(plotTreeBAm2ha=plotTreeBAm2*(10000/672.44),
          plotSapBAm2ha=plotSapBAm2*(10000/(4*13.5))) %>% 
   group_by(PLT_CN) %>% 
          mutate(tBAm2ha=sum(plotTreeBAm2ha,plotSapBAm2ha,na.rm=TRUE)) %>%
   ungroup() %>% 
   mutate(tBAftac=tBAm2ha*4.356) %>% 
  #   filter(PLT_CN==247057536010661) %>%  
    filter(PLT_CN %in% possibles$PLT_CN)
plotout %>% 
  ggplot()+
  geom_point(aes(x=topSTDAGE,y=tBAftac))
  # left_join(fiasp)

# 25_1_11_1005 
# 304152006489998
 trees1short %>% filter(PLT_CN==304152006489998) %>% left_join(fiasp) %>% pull(gesp) %>% unique()
 plotCondft %>% filter(PLT_CN==304152006489998)
 cw <- read.csv("Y:/BigMap/mergedBigMapIC250_filledAltPlotIDcw.csv") %>% rename("SHORT"=filledAltPlotID) #same as above
cw %>% filter(PLT_CN==304152006489998)
 #
#used to create crosswalk filled in fvs codes manually
#fiasp %>% filter(genuspec %in% landisspp$GENUSPEC) %>% filter(! SPCD %in% c(136,317,376,377,378)) %>% write.csv("Y:/FIA/fia_FVScw.csv")
fiafvscw <- read.csv("Y:/FIA/fia_FVScw.csv")
#
```


```{r pull ecoregions from ULSA 90m rasters for chosen fia plots}
library(terra)
eco <- rast("Y:/LANDIS/MA_ulsa_90m_matchedMask/inputFolders/SpatialData/eco_MA90mVccdc.img")
ecoVal <- as.data.frame(values(eco)) 
names(ecoVal) <- "ecoVal"
ic <- rast("Y:/LANDIS/MA_ulsa_90m_matchedMask/inputFolders/SpatialData/IC_MA90mFilledccdc.img")
icVal <- as.data.frame(values(ic)) 
names(icVal) <- "mapcode"
mcSite <- cbind(ecoVal,icVal)
mcSite6393 <- mcSite %>% filter(mapcode==6393) %>% group_by(ecoVal) %>% tally() %>% arrange(desc(n))
mcSite6393
#
```

```{r fvs blank db not on server}
standInit <- read_excel(paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/BlankDatabase.xlsx"),sheet="FVS_StandInit") %>% mutate(VARIANT=as.character(VARIANT)) #Variant as character might not work

names(standInit)
plotInit <- read_excel(paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/BlankDatabase.xlsx"),sheet="FVS_PlotInit") %>% mutate(VARIANT=as.character(VARIANT)) #Variant as character might not work

treeInit <- read_excel(paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/BlankDatabase.xlsx"),sheet="FVS_TreeInit") %>% mutate(TREE_ID=as.character(TREE_ID),SPECIES=as.character(SPECIES))
#
```


```{r fvs blank db  server}
standInit <- read_excel(paste0("Y:/REU2023/FVS/BlankDatabase.xlsx"),sheet="FVS_StandInit") %>% mutate(VARIANT=as.character(VARIANT)) #Variant as character might not work

names(standInit)
plotInit <- read_excel(paste0("Y:/REU2023/FVS/BlankDatabase.xlsx"),sheet="FVS_PlotInit") %>% mutate(VARIANT=as.character(VARIANT)) #Variant as character might not work

treeInit <- read_excel(paste0("Y:/REU2023/FVS/BlankDatabase.xlsx"),sheet="FVS_TreeInit") %>% mutate(TREE_ID=as.character(TREE_ID),SPECIES=as.character(SPECIES))
#
```


```{r pull plots for testing}
maRecentPlotsss <- plotCondft %>% 
  filter(STATE=="MA") %>% 
  filter(PLT_CN %in% mostRecentPlot$PLT_CN) %>% 
  filter(plotAreaForest==672.44) %>% 
  filter(CYCLE>=7) %>% 
  #group_by(ECOSUBCD) %>%  tally() %>% arrange(desc(n))
  filter(ECOSUBCD=="221Ac")
maPossibles <- plotCondft %>% 
  filter(PLT_CN %in% possibles$PLT_CN)
#
# trees
#TODO set up tree table, expand trees and consider having the 4 subplots as ind plots and the stand as the plot cn
treesPrep1 <- trees1short %>% 
  left_join(fiafvscw) %>% 
  filter(STATUSCD==1) %>% 
  ungroup() %>% 
  filter(PLT_CN %in% possibles$PLT_CN) %>% 
  dplyr::select(PLT_CN,INVYR,PLOT,SUBP,TREE,SPCD,FVSsp,DIA,TPA_UNADJ,HT) %>% 
  rename(STAND_ID=PLT_CN,
         TREE_COUNT=TPA_UNADJ,
         DIAMETER=DIA) %>% 
  mutate(PLOT_ID=1,
         TREE_ID=paste0(SUBP,TREE))
plotsWnonLandisspp <- treesPrep1 %>% filter(is.na(FVSsp)) %>% pull(STAND_ID) %>% unique()  
trees <- treesPrep1 %>%
  filter(!STAND_ID %in% plotsWnonLandisspp) %>% 
  rename(SPECIES=FVSsp) %>% 
  dplyr::select(-SPCD)
#
#stands <- maRecentPlotsss %>% 
stands <- maPossibles %>% 
  rename(STAND_ID=PLT_CN,
        INV_YEAR=INVYR,
        LATITUDE=LAT,
        LONGITUDE=LON,

        ELEVFT = ELEV #this is feet #can also add slope and aspect

        
        ) %>% 
  mutate(         LOCATION=922,
                  VARIANT="NE",
                   NUM_PLOTS=1,
        BRK_DBH=999, #manually expand trees in tree table
        INV_PLOT_SIZE=plotAreaForest/4047, #m2 to acres
         #MAX_BA=
          ) %>% 
  ungroup() %>% 
  dplyr::select(#GROUPS=concatPlot,
                STAND_ID,
                INV_YEAR,
                LATITUDE,
                LONGITUDE,
                LOCATION,
                VARIANT,
                NUM_PLOTS,BRK_DBH,INV_PLOT_SIZE,SITE_INDEX=topSICOND
                ) %>% 
  filter(STAND_ID %in% trees$STAND_ID)
#
plots <- maPossibles %>% 
  rename(STAND_ID=PLT_CN,
           INV_YEAR=INVYR,
        LATITUDE=LAT,
        LONGITUDE=LON,
        ELEVFT = ELEV, #this is feet #can also add slope and aspect
        ECOREGION = ECOSUBCD, #this is not actually used in the NE variant
        
        ) %>% 
  mutate(PLOT_ID=1, 
         LOCATION=922,
                  VARIANT="NE",
                   NUM_PLOTS=4,
        BRK_DBH=999, #manually expand trees in tree table
        INV_PLOT_SIZE=plotAreaForest/4047, #m2 to acres
         #MAX_BA=
          ) %>% 
  ungroup() %>% 
  dplyr::select(#GROUPS=concatPlot,
                STAND_ID,
                PLOT_ID,
                INV_YEAR,
                LATITUDE,
                LONGITUDE,
                LOCATION,
                VARIANT,
                NUM_PLOTS,
                BRK_DBH,
                INV_PLOT_SIZE,
                SITE_INDEX=topSICOND,
                # MAXBA=  #maximum BA (ft2 per acre)
                )  %>% 
  filter(STAND_ID %in% trees$STAND_ID)
#
#

standInitOut <- standInit %>% bind_rows(stands) %>% mutate(STAND_ID=as.character(STAND_ID))
plotInitOut <- plotInit %>% bind_rows(plots) %>% mutate(STAND_ID=as.character(STAND_ID))
treeInitOut <- treeInit %>% bind_rows(trees) %>% mutate(STAND_ID=as.character(STAND_ID))
runName <- "MA_mbb"
library(xlsx) #needed to install 64 bit java for this to work
write.xlsx(standInitOut,
           file= paste0("Y:/REU2023/FVS/01_processedInputData/",runName,".xlsx"),
           sheetName="FVS_StandInit",
           showNA = FALSE)

#
write.xlsx(plotInitOut,
           file= paste0("Y:/REU2023/FVS/01_processedInputData/",runName,".xlsx"),
           sheetName="FVS_PlotInit",
           showNA = FALSE,
           append = TRUE)
#
write.xlsx(treeInitOut,
           file= paste0("Y:/REU2023/FVS/01_processedInputData/",runName,".xlsx"),
           sheetName="FVS_TreeInit",
           showNA = FALSE,
           append = TRUE)
#
```


```{r max BA and relBA prep with new source inputs}

trees1short <- alltrees %>% 
  filter(INVYR>=1999) %>% 
  
  filter(SUBP<=4) %>% #data for subp numbers greater than 4 are coearsed into the 1-4 design and duplicated - so removing 3/3/23
  
  dplyr::select(INVYR,STATECD,UNITCD,COUNTYCD,PLOT,PLT_CN,SUBP,TREE,CN,STATUSCD,SPCD,SITREE,DIA,TPA_UNADJ,CARBON_AG,HT,ACTUALHT,TREECLCD,AGENTCD) %>% 
  unite(concatPlot,STATECD,UNITCD,COUNTYCD,PLOT,sep="_",remove=FALSE) %>% 
  mutate(AGCg=CARBON_AG*453.592,
         AGCMg=AGCg*gramToMegagram,
         actHeight=ifelse(ACTUALHT==-Inf,NA,ACTUALHT),
         sizeClass = ifelse(DIA>=5,"tree","sap"),
         diacm=DIA*2.54,
         BAm2=pi*(.5*(diacm)/100)^2
  ) %>% 
  group_by(concatPlot,PLOT,SUBP,TREE,CN) %>% 
  arrange(concatPlot,PLOT,SUBP,TREE,CN,INVYR) %>% 
  mutate(treeBAI=(BAm2-lag(BAm2)/(INVYR-lag(INVYR))),Growth_Cg=(AGCg-lag(AGCg)/(INVYR-lag(INVYR)))) 
#
 a <- trees1short %>% left_join(plotCondft) %>% filter(!is.na(meanSICOND)) %>% group_by(SPCD,sizeClass) %>% summarise(maxBAm2=max(BAm2,na.rm=TRUE),lowSI=quantile(meanSICOND,probs=.05),medSI=quantile(meanSICOND,probs=.5),highSI=quantile(meanSICOND,probs=.9))%>% mutate(maxBAft2=maxBAm2*10.76391) 
#
 fiasp <- fia %>% mutate(genuspec=tolower(genuspec))
 b <- a %>% left_join(fiasp) %>% right_join(landisspp)
 #
treesout <- trees1short %>% 
  filter(DIA>=5) %>% 
  filter(STATUSCD==1) %>% 
   right_join(plotCondft) %>%
  ungroup() %>% 
   group_by(concatPlot,PLT_CN,INVYR) %>% 
   mutate(plotBAm2=sum(BAm2,na.rm=TRUE)) %>% 
   ungroup() %>% 
  group_by(STATE,concatPlot,PLT_CN,INVYR,plotBAm2,SPCD,plotAreaForest) %>% 
  summarise(spBAm2=round(sum(BAm2,na.rm=TRUE),3)) %>% 
   mutate(relBA=round(spBAm2/plotBAm2,3),
          spBAm2ha=spBAm2*(10000/plotAreaForest)) %>% 
  left_join(fiasp) 
#
todf <- treesout %>% 
  filter(relBA>=0.4) %>% 
  group_by(STATE,SPCD,gesp) %>% 
  summarise(meanspBAm2ha=round(mean(spBAm2ha,na.rm=TRUE),2),
            maxspBAm2ha=round(max(spBAm2ha,na.rm=TRUE),2),
            nplotswdom=length(gesp),
            q=c(.05,.5,.95),
            spBAm2ha=round(quantile(spBAm2ha,c(.05,.5,.95),na.rm=TRUE) ,3)) %>% 
  filter(nplotswdom>=10) %>% 
  pivot_wider(id_cols=c(STATE,SPCD,gesp,meanspBAm2ha,maxspBAm2ha,nplotswdom),names_from=q,values_from=spBAm2ha,names_prefix="spBAm2ha_") %>% 
  #pivot_wider(id_cols=c(SPCD,gesp),values_from=c(meanspBAm2ha,maxspBAm2ha),names_from=STATE)
  arrange(gesp,STATE)
  
todf %>% 
  filter(STATE=="MA") %>% 
  ggplot(aes(x=reorder(gesp,spBAm2ha_0.95),y=spBAm2ha_0.95,fill=STATE)) +
  geom_col(position="dodge")+
  theme_bw() +
  theme(axis.text.x=element_text(angle=90,vjust=-.1)) 

#

```


```{r pressure, echo=FALSE}
 # treesout %>% group_by(PLT_CN) %>% summarise(tBAm2ha=sum(BAm2ha,na.rm=TRUE),tAGCMgha=sum(AGCMgha,na.rm=TRUE))
 # summary( treesout %>% group_by(PLT_CN) %>% summarise(tBAm2ha=sum(BAm2ha,na.rm=TRUE),tAGCMgha=sum(AGCMgha,na.rm=TRUE)))

```

