---
title: "fvsOutput"
author: "Danelle Laflower"
date: '2022-09-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
source("Y:/LANDIS/Rcode/landis_source.R")

#
```

```{r}
whichComputer <-  "dml486" #"danel" # 
defaultFVSdirectory <- paste0("C:/Users/",whichComputer,"/Downloads/")
#
```


```{r fvs output}
#plot level


#output directory
outputDir <- "Y:/REU2023/FVS/03_outputs"
runName <- "Run 6"  #"fia6993" # "Run 1"  #"tpa1000_initiation"  #tpa and then defining run
cOut <- read_excel(paste0("C:/Users/",whichComputer,"/Downloads/",runName,"_FVSoutput20230725.xlsx"),sheet="FVS_Carbon") %>% 
  dplyr::select(CaseID,StandID,Year,Aboveground_Total_Live,Belowground_Live,Standing_Dead,Belowground_Dead,Forest_Down_Dead_Wood)
cOut %>% group_by(StandID) %>% 
  slice(1) %>% 
  dplyr::select(StandID,Year,Aboveground_Total_Live) %>% 
  mutate(AGMgha=Aboveground_Total_Live*2.2417) %>% 
  saveRDS(paste0(outputDir,"mbbV3_20230725.Rds"))

bOut <- read_excel(paste0("C:/Users/",whichComputer,"/Downloads/",runName,"_FVSoutput.xlsx"),sheet="FVS_Summary2_East") %>% 
  dplyr::select(StandID,CaseID,Year,Age,Tpa,BA,SDI,TopHt)
bcOut <- cOut %>% left_join(bOut)
head(bcOut)
write.csv(bcOut, paste0(outputDir,"/",runName,"_FVSoutput.csv") )
#write.csv(bcOut,paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/outputs/",runName,".csv"))
#tree level
tOut <- read_excel(paste0("C:/Users/",whichComputer,"/Downloads/",runName,"_FVSoutput.xlsx"),sheet="FVS_TreeList_East") 

# for calibration
cOut %>% #NE922-1000_FVSoutput (1).xlsx
  mutate(gesp=substr(StandID,1,4),
         si=substr(StandID,6,8),
         gespSpecifics=substr(StandID,6,nchar(StandID)) ) %>% 
#filter(si=="Med") %>% 
  ggplot(aes(x=Year,y=abgCMgha,color=gespSpecifics)) + 
  geom_line(lwd=1) +
  geom_point() +
  #scale_color_manual(values=cols)+
  facet_wrap(~gesp) +
  theme_bw()
#

# open multiple files
lfcs <- list.files(defaultFVSdirectory,pattern="FVSoutput.xlsx")

#lfcs <- lfcs[c(1,3,4,5,7)]
lfcs
setwd(defaultFVSdirectory); fvsSummaryTableOut <- map_dfr(.x=set_names(lfcs),
               .f=read_excel, sheet="FVS_Summary2_East",
               .id="source_file") %>% 
  separate(source_file,c("regionRun",NA),sep="_FVS",remove=FALSE) %>% 
  group_by(StandID) %>% 
  arrange(StandID,Year)
fvsSummaryTableOut %>% filter(Year==2016)
fvsSummaryTableOut %>% filter(Year==2023)
head(fvsSummaryTableOut)
table(fvsSummaryTableOut$regionRun)
#
fvsSummaryTableOut %>% 
  group_by(StandID) %>% 
  mutate(tBA=sum(BA,na.rm=TRUE)) %>% 
  filter(tBA>0) %>% 
  ggplot(aes(x=Year,y=BA,color=regionRun)) +
  geom_smooth()

#outputDir <- paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/outputs")
#outputDir <- paste0("C:/Users/",whichComputer,"/Downloads")
#lfcs <- list.files(defaultFVSdirectory,pattern="FVSoutput.xlsx")
setwd(defaultFVSdirectory); fvsout <- map_dfr(.x=set_names(lfcs2),
               .f=read_excel, sheet="FVS_Carbon",
               .id="source_file") %>% 
  separate(source_file,c("regionRun",NA),sep="_FVS",remove=FALSE)  %>% 
  #separate(simuID,c("varReg","tpa"),remove="FALSE") %>% 

   dplyr::select(regionRun,StandID,Year,Aboveground_Total_Live) %>% # ,varReg, ,tpa
  #aboveground total live is in tonne/ac
  mutate(abgCMgAc= Aboveground_Total_Live*0.9071847,
         abgCMgha= abgCMgAc*2.47) # %>% 
  #for single species calibration runs
   # mutate(
   #       #gesp=substr(StandID,1,4),
   #       #si=substr(StandID,6,8),
   #       #tpha=as.integer(tpa)*2.47,
   #       #"trees per ha"=as.character(tpha),
   #       #gespSpecifics=substr(StandID,6,nchar(StandID))
   #       ) %>% 
   #  unite("group",'simuID','gespSpecifics',remove=FALSE) 
#
head(fvsout)
fvsout %>% 
  group_by(StandID) %>% 
  mutate(tAGL=sum(Aboveground_Total_Live,na.rm=TRUE)) %>% 
  filter(tAGL>0) %>% 
  ggplot(aes(x=Year,y=Aboveground_Total_Live,color=regionRun)) +
  geom_smooth()
# fvsout %>% 
#   filter(gespSpecifics %in% c("LowMaxBA","MedMaxBA","HighMaxBA")) %>% 
#   filter(gesp %in% c("ACSA","ACRU","QURU","PIST")) %>% 
#   filter(simuID %in% c("LS909-200","LS909-1000")) %>% # "NE922ne-1000","NE922ne-200", ,"LS909-2000"
#   mutate(productivityClass=ifelse(gespSpecifics=="LowMaxBA","low",
#                                   ifelse(gespSpecifics=="MedMaxBA","medium","high")),
#          productivityClass = factor(productivityClass,levels=c("high","medium","low"))) %>% 
#     #filter(si=="Med") %>% 
#   ggplot(aes(x=Year,y=abgCMgha,color=productivityClass,linetype=`trees per ha`)) + 
#   geom_line(lwd=1) +
#   theme_bw()+
#   scale_x_continuous(limits=c(2020,2100))+
#   #geom_point() +
#   facet_wrap(~gesp)

#
lfcs2 <- lfcs[c(1,3)]
setwd(defaultFVSdirectory); fvsTreeListOut <- map_dfr(.x=set_names(lfcs2),
               .f=read_excel, sheet="FVS_TreeList_East",
               .id="source_file") %>% 
  separate(source_file,c("regionRun",NA),sep="_FVS",remove=FALSE) %>% 
  group_by(StandID) %>% 
  arrange(StandID,Year)
fvsTreeListOut %>% filter(Year==2016) %>% arrange(SpeciesFIA,DBH)
fvsTreeListOut %>% filter(Year==2023) %>% arrange(StandID,SpeciesFIA,DBH)
fvsSummaryTableOut %>% filter(Year==2023)
fvsSummaryTableOut %>% filter(Year==2016)
head(fvsSummaryTableOut)
table(fvsSummaryTableOut$regionRun)

#

  
```

```{r output,echo=FALSE,fig.height=10,fig.width=12}
fvsout %>% 
  #filter(si=="Med") %>% 
  ggplot(aes(x=Year,y=abgCha,linetype=tpa,color=group)) + 
  geom_line(lwd=1) +
  geom_point() +
  #scale_color_manual(values=cols)+
  facet_wrap(~gesp) +
  theme_bw()
#
```

```{r fia prep with new source inputs}
source("Y:/FIA/Rcode/FIA_ImportAndProcess_notTrees.R")
source("Y:/FIA/Rcode/fia_source_treesSUBSET.R") #currently New England is the default.  manually set before running
trees1short <- alltrees %>% 
  filter(INVYR>=1999) %>% 
  
  filter(SUBP<=4) %>% #data for subp numbers greater than 4 are coearsed into the 1-4 design and duplicated - so removing 3/3/23
  
  dplyr::select(INVYR,STATECD,UNITCD,COUNTYCD,PLOT,PLT_CN,SUBP,TREE,CN,STATUSCD,SPCD,SITREE,DIA,TPA_UNADJ,CARBON_AG,HT,ACTUALHT,TREECLCD,AGENTCD) %>% 
  unite(concatPlot,STATECD,UNITCD,COUNTYCD,PLOT,sep="_",remove=FALSE) %>% 
  mutate(AGCg=CARBON_AG*453.592,
         AGCMg=AGCg*gramToMegagram,
         actHeight=ifelse(ACTUALHT==-Inf,NA,ACTUALHT),
         sizeClass = ifelse(DIA>=5,"tree","sap"),
         diacm=DIA*2.54,
         BAm2=pi*(.5*(diacm)/100)^2
  ) %>% 
  group_by(concatPlot,PLOT,SUBP,TREE,CN) %>% 
  arrange(concatPlot,PLOT,SUBP,TREE,CN,INVYR) %>% 
  mutate(treeBAI=(BAm2-lag(BAm2)/(INVYR-lag(INVYR))),Growth_Cg=(AGCg-lag(AGCg)/(INVYR-lag(INVYR)))) 
#
 a <- trees1short %>% left_join(plotCondft) %>% filter(!is.na(meanSICOND)) %>% group_by(SPCD) %>% summarise(maxBAm2=max(BAm2,na.rm=TRUE),lowSI=quantile(meanSICOND,probs=.05),medSI=quantile(meanSICOND,probs=.5),highSI=quantile(meanSICOND,probs=.9))%>% mutate(maxBAft2=maxBAm2*10.76391) 
#
 fiasp <- fia %>% mutate(genuspec=tolower(genuspec))
 b <- a %>% left_join(fiasp) %>% right_join(landisspp)
 #
treesout <- trees1short %>% 
  filter(DIA>=5) %>% 
  filter(STATUSCD==1) %>% 
   right_join(plotCondft) %>%
  ungroup() %>% 
   group_by(concatPlot,PLT_CN,INVYR) %>% 
   mutate(plotBAm2=sum(BAm2,na.rm=TRUE)) %>% 
   ungroup() %>% 
  group_by(STATE,concatPlot,PLT_CN,INVYR,plotBAm2,SPCD,plotAreaForest) %>% 
  summarise(spBAm2=round(sum(BAm2,na.rm=TRUE),3)) %>% 
   mutate(relBA=round(spBAm2/plotBAm2,3),
          spBAm2ha=spBAm2*(10000/plotAreaForest)) %>% 
  left_join(fiasp) 
#
todf <- treesout %>% 
  filter(relBA>=0.4) %>% 
  group_by(STATE,SPCD,gesp) %>% 
  summarise(meanspBAm2ha=round(mean(spBAm2ha,na.rm=TRUE),2),
            maxspBAm2ha=round(max(spBAm2ha,na.rm=TRUE),2),
            nplotswdom=length(gesp),
            q=c(.05,.5,.95),
            spBAm2ha=round(quantile(spBAm2ha,c(.05,.5,.95),na.rm=TRUE) ,3)) %>% 
  filter(nplotswdom>=10) %>% 
  pivot_wider(id_cols=c(STATE,SPCD,gesp,meanspBAm2ha,maxspBAm2ha,nplotswdom),names_from=q,values_from=spBAm2ha,names_prefix="spBAm2ha_") %>% 
  #pivot_wider(id_cols=c(SPCD,gesp),values_from=c(meanspBAm2ha,maxspBAm2ha),names_from=STATE)
  arrange(gesp,STATE)
  
todf %>% 
  filter(STATE=="MA") %>% 
  ggplot(aes(x=reorder(gesp,spBAm2ha_0.95),y=spBAm2ha_0.95,fill=STATE)) +
  geom_col(position="dodge")+
  theme_bw() +
  theme(axis.text.x=element_text(angle=90,vjust=-.1)) 

#

```

```{r fvs blank db}
standInit <- read_excel(paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/BlankDatabase.xlsx"),sheet="FVS_StandInit") %>% mutate(VARIANT=as.character(VARIANT)) #Variant as character might not work

names(standInit)
plotInit <- read_excel(paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/BlankDatabase.xlsx"),sheet="FVS_PlotInit")

treeInit <- read_excel(paste0("C:/Users/",whichComputer,"/Dropbox (Harvard University)/danellelaflower/fvs/BlankDatabase.xlsx"),sheet="FVS_TreeInit")
```

```{r pull plots for testing}
maRecentPlotsss <- plotCondft %>% 
  filter(STATE=="MA") %>% 
  filter(PLT_CN %in% mostRecentPlot$PLT_CN) %>% 
  filter(plotAreaForest==672.44) %>% 
  filter(CYCLE>=7) %>% 
  #group_by(ECOSUBCD) %>%  tally() %>% arrange(desc(n))
  filter(ECOSUBCD=="221Ac")
stands <- maRecentPlots %>% 
  rename(STAND_ID=PLT_CN,
        INV_YR=INVYR,
        LATITUDE=LAT,
        LONGITUDE=LON,

        ELEVFT=ELEV#this is feet #can also add slope and aspect

        
        ) %>% 
  mutate(         LOCATION=922,
                  VARIANT="NE",
                   NUM_PLOTS=1,
        BRK_DBH=999, #manually expand trees in tree table
        INV_PLOT_SIZE=plotAreaForest/4047, #m2 to acres
         #MAX_BA=
          ) %>% 
  ungroup() %>% 
  dplyr::select(STAND_ID,INV_YR,LATITUDE,LONGITUDE,LOCATION,VARIANT,NUM_PLOTS,BRK_DBH,INV_PLOT_SIZE)
#
standInit %>% bind_rows(stands)
#
```


```{r fia prep for NE, echo=FALSE}
source("Y:/FIA/Rcode/FIA_ImportAndProcess_sourceSHORT.R")
 a <- trees1 %>% left_join(cond1) %>% filter(!is.na(SICOND)) %>% group_by(SPCD) %>% summarise(BAMAX=max(BAm2),low=quantile(SICOND,probs=.05),med=quantile(SICOND,probs=.5),high=quantile(SICOND,probs=.9))%>% mutate(maxBAft2=maxBAm2*10.76391)
b <- a %>% left_join(fia) %>% left_join(landisspp)
#
```

#for joe temp
```{r}
nerasagcmgha <- raster::raster("Y:/BigMap/mergedBigMapIC250_filledAltPlotIDAGCMghaFullsubpArea2022-05-26.tif")
agcVal <- raster::getValues(nerasagcmgha)
df <- as.data.frame(agcVal) %>% filter(!is.na(agcVal)) %>% mutate(name="ic")
ggplot(df,aes(x=name,y=agcVal)) +
  geom_boxplot()
#
```

