---
title: "Nunery Keeton Revisited"
author: "Nikolaus Bates-Haus"
output:
  pdf_document: default
  html_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
library(tidyverse)
library(RSQLite)
library(dbplyr)
```


# Introduction

In [@nunery2010], different management regimens were modeled to explore
their impact on carbon storage. This study used the Forest Vegetation
Simulator (FVS) to model carbon storage. Other models exist to predict
carbon storage; we seek to compare FVS with other models to understand
their different predictions for carbon storage under different
management regimens.

# Database Preparation

This project depends heavily on the SQLite version of the FIA data, distributed
as SQLite_FIADB_ENTIRE.db. Place a copy of this file in data/raw/
The database ships with most indexes missing, which makes most queries very slow.

## Primary and Foreign Keys

Most tables with a simple primary key name that key "CN", for Control Number.
Many tables have foreign keys named <table abbreviation>_CN.
Create indexes on primary and foreign keys to speed up joins.

Note that some tables have a CN column that is not a primary key. Rather
than manage this, we create the primary key indexes witout the UNIQUE
constraint. This does not change the structure of the index, but may impact
query plans.

## Plot Identifiers

Many tables have the three columns that uniquely identify a plot:
STATECD, COUNTYCD, PLOT
Index those because we often want to look up all the records pertaining to
a plot by location.

If a table also has INVYR, this uniquely identifies a plot at a point of time.
Index those too.
