---
title: "Nunery Keeton Revisited"
author: "Nikolaus Bates-Haus"
output:
  pdf_document: default
  html_document: default
editor_options:
  markdown:
    wrap: 72
---

# References

1.  Nunery, Jared & Keeton, William. (2010). Forest carbon storage in
    the northeastern United States: Net effects of harvesting frequency,
    post-harvest retention, and wood products. Forest Ecology and
    Management. 259. 1363-1375. 10.1016/j.foreco.2009.12.029.

2.  Shaw, John & Gagnon, Aaron. (2019). Field Note: A New Conversion of
    Forest Inventory and Analysis Data for Use in the Forest Vegetation
    Simulator. Journal of Forestry. 118. 10.1093/jofore/fvz050.

3.  Burrill, Elizabeth A.; DiTommaso, Andrea M.; Turner, Jeffery A.;
    Pugh, Scott A.; Christensen, Glenn; Perry, Carol J.; Lepine, Lucie
    C.; Walker, David M.; Conkling, Barbara L. 2024. The Forest
    Inventory and Analysis Database, FIADB user guides, volume database
    description (version 9.2), nationwide forest inventory (NFI). U.S.
    Department of Agriculture, Forest Service. 1042 p. [Online].
    Available at web address:
    <https://www.fs.usda.gov/research/products/dataandtools/datasets/fia-datamart>

4.  Shaw, John D. & Gagnon, Aaron. (2020). Quick-Start Guide to Forest
    Inventory Analysis Data in the Forest vegetation Simulator. U.S.
    Department of Agriculture, Forest Service. 25 p. [Online]. Available
    at web address:
    <https://www.fs.usda.gov/fvs/documents/FIA_Data_Quick_Start_Guide_20200914.pdf>

5.  Ethan P Belair, Mark J Ducey, Patterns in Forest Harvesting in New
    England and New York: Using FIA Data to Evaluate Silvicultural
    Outcomes, Journal of Forestry, Volume 116, Issue 3, May 2018, Pages
    273–282, <https://doi.org/10.1093/jofore/fvx019>

6.  FVS Staff. 2008 (revised April 16, 2024). Northeast (NE) Variant
    Overview – Forest Vegetation Simulator. Internal Rep. Fort Collins,
    CO: U. S. Department of Agriculture, Forest Service, Forest
    Management Service Center. 56p. 
    <https://www.fs.usda.gov/fmsc/ftp/fvs/docs/overviews/FVSne_Overview.pdf>

7.  FVS Staff. 2021. FVS Training Guide. Fort Collins,
    CO: U. S. Department of Agriculture, Forest Service, Forest
    Management Service Center. 142p. 
    <https://www.fs.usda.gov/fvs/documents/FVSTrainingGuide-20210930.pdf>
    
8.  Herbert, C.; Fried, J.S.; Butsic, V. Validation of Forest Vegetation
    Simulator Model Finds Overprediction of Carbon Growth in California.
    Forests 2023, 14, 604. https://doi.org/10.3390/f14030604